trigger:
- main

pool:
  name: Default 

variables:
  resourceGroupName: 'my-linux-vm-rg' 
  location: 'Central US'               
  deploymentName: 'DeployLinuxVM'      

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'arm-template'  
    scriptType: 'pscore'  # Change from 'bash' to 'pscore' (PowerShell Core)
    scriptLocation: 'inlineScript'
    inlineScript: |
      az account set --subscription 83f5959f-2f46-4a86-9006-cb2e23ff3bd7
      az group create --name $(resourceGroupName) --location "$(location)"


# Deploy ARM Template
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'              
    azureResourceManagerConnection: 'arm-template'  
    subscriptionId: '83f5959f-2f46-4a86-9006-cb2e23ff3bd7'       
    resourceGroupName: '$(resourceGroupName)'      
    location: '$(location)'                        
    templateLocation: 'Linked artifact'            
    csmFile: '$(Build.SourcesDirectory)/templates/azuredeploy.json' 
    csmParametersFile: '$(Build.SourcesDirectory)/templates/azuredeploy.parameters.json'  
    deploymentMode: 'Incremental'                  
    deploymentName: '$(deploymentName)'  
